### ISSUE TITLE
Perhaps catfile should be set to catfile = usnob1.spec

### ISSUE THREAD

**Issue by astro-jingtao** [mdcleir/DRESSCode#1]
Perhaps `catfile` should be set to `catfile = 'usnob1.spec'`

https://github.com/mdecleir/DRESSCode/blob/b078d5a76f4eb0b2f543eaad5168f08e1f001b51/uvotskycorr.py#L41
https://github.com/mdecleir/DRESSCode/blob/b078d5a76f4eb0b2f543eaad5168f08e1f001b51/uvotskycorr2.py#L44

**Comment by mdecleir** [comment]
Hello,

Thank you for the suggestion.
I agree that the path to the file should be updated to reflect the current file structure in the repository.
I will fix this as soon as possible.

However, if you are interested in using DRESSCode, I would like to point out that this software has been moved to https://github.com/spacetelescope/DRESSCode, where it has been updated significantly, and is still in active development.
The version here is a previous, but stable version, and will not be updated in the future. I will add a comment about this in the README file.

Best wishes,
Marjorie

**Comment by astro-jingtao** [comment]
Thanks for letting me know the repository of active version of DRESSCode.
